INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Cheeseburger', 0);
INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Monsterburger', 0);
INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Jr. Burger', 1);
